language: rust
sudo: false
dist: trusty

rust:
  - nightly
  - beta
  - stable
  - 1.10.0
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

cache:
  apt: true
  cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

before_script: |
  (which cargo-coverage || cargo install cargo-travis) &&
  export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    set -e
    if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo bench --verbose | tee benches-variable
      git config remote.origin.fetch "+refs/heads/master:refs/remotes/origin/master"
      git remote update
      git checkout -b master origin/master
      cargo bench --verbose | tee benches-control
      (which cargo-benchcmp || cargo install cargo-benchcmp)
      cargo benchcmp benches-control benches-variable
    fi

after_success: |
  cargo coverage -m ../kcov &&
  bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
