language: rust
sudo: false
dist: trusty

rust:
  - nightly
  - beta
  - stable
  - 1.10.0
matrix:
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - '[ $TRAVIS_RUST_VERSION != nightly ] || cargo bench'

after_success: |
  set -e
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
  cmake .. && make && make install DESTDIR=../../kcov-build && cd ../..
  RUSTFLAGS="-C link-dead-code" cargo test --no-run
  for file in target/debug/parsip-*[^\.d]; do
    mkdir -p "target/cov/$(basename $file)";
    ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file";
  done
  bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
